[controller]
name = "Joycon (R)"
base = "images/Base.webp"
icon = "images/Icon.webp"

# ── Input Modes ──

[[modes]]
name = "joyconr"
vendor = "057e"
product = "2007"

# ── System Buttons ──

[[buttons]]
id = "plus"
image = "images/Buttons/Plus.webp"
input = { type = "button", index = 6 }

[[buttons]]
id = "home"
image = "images/Buttons/Home.webp"
input = { type = "button", index = 5 }

# ── D-Pad ──

[[buttons]]
id = "a"
image = "images/Buttons/A.webp"
input = { type = "button", index = 0 }

[[buttons]]
id = "b"
image = "images/Buttons/B.webp"
input = { type = "button", index = 2 }

[[buttons]]
id = "x"
image = "images/Buttons/X.webp"
input = { type = "button", index = 1 }

[[buttons]]
id = "y"
image = "images/Buttons/Y.webp"
input = { type = "button", index = 3 }

# ── Shoulder Buttons ──

[[buttons]]
id = "r"
image = "images/Buttons/R.webp"
input = { type = "button", index = 16 }

[[buttons]]
id = "slr"
image = "images/Buttons/SLR.webp"
input = { type = "button", index = 9 }

[[buttons]]
id = "srr"
image = "images/Buttons/SRR.webp"
input = { type = "button", index = 10 }

# ── Analog Triggers ──

[[buttons]]
id = "zr"
image = "images/Buttons/ZR.webp"
input = { type = "button", index = 18 }

# ── Analog Sticks ──

[[buttons]]
id = "rs"
image = "images/Buttons/RS.webp"
input = { type = "stick", axis_x = 0, axis_y = 1, press_button = 7 }
